from __future__ import annotations

from io import BytesIO
from pathlib import Path

import pytest
from pypdf import PdfWriter

from dmc_sidecar import config
from dmc_sidecar.errors import DomainError
from dmc_sidecar.typhoon_ocr import TyphoonOcrDmcFormRequest, ocr_dmc_form_with_typhoon


def _pdf_with_pages(page_count: int) -> bytes:
    stream = BytesIO()
    writer = PdfWriter()
    for _ in range(page_count):
        writer.add_blank_page(width=72, height=72)
    writer.write(stream)
    return stream.getvalue()


def test_ocr_dmc_form_with_typhoon_writes_markdown_and_uses_cache(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setattr(config, "default_data_dir", lambda: tmp_path / "data")
    monkeypatch.setattr("dmc_sidecar.typhoon_ocr.TYPHOON_OCR_PAGE_DELAY_SECONDS", 0)
    source_path = tmp_path / "form.pdf"
    source_path.write_bytes(_pdf_with_pages(2))
    pages: list[tuple[Path, int]] = []

    def fake_ocr_page(
        source: Path,
        *,
        api_key: str,
        base_url: str,
        model: str,
        page_number: int,
    ) -> str:
        pages.append((source, page_number))
        assert source != source_path
        assert source.exists()
        assert api_key == "secret"
        assert base_url == "https://api.opentyphoon.ai/v1"
        assert model == "typhoon-ocr"
        assert page_number == 1
        if len(pages) == 1:
            return "เลขประจำตัวประชาชน* 1810800164491\nเลขประจำตัวนักเรียน 20018"
        return "คำนำหน้านาม* เด็กชาย\nเพศ* ชาย"

    monkeypatch.setattr("dmc_sidecar.typhoon_ocr._ocr_page_with_typhoon", fake_ocr_page)

    response = ocr_dmc_form_with_typhoon(
        TyphoonOcrDmcFormRequest(source_path=str(source_path), api_key="secret", model="typhoon-ocr")
    )

    markdown_path = Path(response.markdown_path)
    assert response.cached is False
    assert response.pages_processed == 2
    assert response.pages_estimated == 2
    assert response.credits_per_page == 3
    assert response.credits_charged == 0
    assert response.charged is False
    assert response.average_confidence is None
    assert markdown_path.exists()
    markdown = markdown_path.read_text(encoding="utf-8")
    assert "Generated by DMC Assistant from Typhoon OCR" in markdown
    assert "เลขประจำตัวประชาชน* 1810800164491" in markdown

    cached_response = ocr_dmc_form_with_typhoon(TyphoonOcrDmcFormRequest(source_path=str(source_path)))

    assert cached_response.cached is True
    assert cached_response.markdown_path == response.markdown_path
    assert cached_response.credits_charged == 0
    assert [page.name for page, _page_number in pages] == ["page-0001.pdf", "page-0002.pdf"]


def test_ocr_dmc_form_with_typhoon_handles_classroom_sized_pdf_by_splitting(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setattr(config, "default_data_dir", lambda: tmp_path / "data")
    monkeypatch.setattr("dmc_sidecar.typhoon_ocr.TYPHOON_OCR_PAGE_DELAY_SECONDS", 0)
    source_path = tmp_path / "classroom-registration.pdf"
    source_path.write_bytes(_pdf_with_pages(45))
    calls: list[tuple[Path, int]] = []

    def fake_ocr_page(
        source: Path,
        *,
        api_key: str,
        base_url: str,
        model: str,
        page_number: int,
    ) -> str:
        del api_key, base_url, model
        calls.append((source, page_number))
        assert source != source_path
        assert source.exists()
        assert page_number == 1
        return f"ทะเบียนบ้านหน้า {len(calls)}"

    monkeypatch.setattr("dmc_sidecar.typhoon_ocr._ocr_page_with_typhoon", fake_ocr_page)

    response = ocr_dmc_form_with_typhoon(
        TyphoonOcrDmcFormRequest(source_path=str(source_path), api_key="secret", model="typhoon-ocr")
    )

    assert response.pages_processed == 45
    assert response.pages_estimated == 45
    assert len(calls) == 45
    assert [page.name for page, _page_number in calls[:3]] == ["page-0001.pdf", "page-0002.pdf", "page-0003.pdf"]
    markdown = Path(response.markdown_path).read_text(encoding="utf-8")
    assert "<!-- Page 45 confidence: n/a -->" in markdown


def test_ocr_dmc_form_with_typhoon_requires_api_key_when_not_cached(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setattr(config, "default_data_dir", lambda: tmp_path / "data")
    source_path = tmp_path / "form.pdf"
    source_path.write_bytes(_pdf_with_pages(1))

    with pytest.raises(DomainError) as exc_info:
        ocr_dmc_form_with_typhoon(TyphoonOcrDmcFormRequest(source_path=str(source_path)))
    assert exc_info.value.code == "TYPHOONOCR_API_KEY_REQUIRED"


def test_ocr_dmc_form_with_typhoon_rejects_pdf_when_page_count_is_unknown(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setattr(config, "default_data_dir", lambda: tmp_path / "data")
    source_path = tmp_path / "form.pdf"
    source_path.write_bytes(b"%PDF-1.7\ncompressed or unsupported page tree\n%%EOF")

    with pytest.raises(DomainError) as exc_info:
        ocr_dmc_form_with_typhoon(TyphoonOcrDmcFormRequest(source_path=str(source_path), api_key="secret"))
    assert exc_info.value.code == "TYPHOONOCR_PAGE_COUNT_UNKNOWN"


def test_ocr_dmc_form_with_typhoon_rejects_unsupported_file(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setattr(config, "default_data_dir", lambda: tmp_path / "data")
    source_path = tmp_path / "form.webp"
    source_path.write_text("not uploadable", encoding="utf-8")

    with pytest.raises(DomainError) as exc_info:
        ocr_dmc_form_with_typhoon(TyphoonOcrDmcFormRequest(source_path=str(source_path), api_key="secret"))
    assert exc_info.value.code == "TYPHOONOCR_UNSUPPORTED_INPUT_TYPE"
