from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from dmc_sidecar import config
from dmc_sidecar.akson_ocr import AksonOcrDmcFormRequest, ocr_dmc_form_with_akson
from dmc_sidecar.errors import DomainError


def test_ocr_dmc_form_with_akson_writes_markdown_and_uses_cache(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setattr(config, "default_data_dir", lambda: tmp_path / "data")
    source_path = tmp_path / "form.pdf"
    source_path.write_bytes(b"%PDF-1.7\nsample dmc form\n")
    uploads: list[Path] = []

    def fake_upload(source: Path, *, api_key: str, model: str) -> dict[str, Any]:
        uploads.append(source)
        assert api_key == "secret"
        assert model == "AksonOCR-1.0"
        return {
            "model": model,
            "pages": [
                {
                    "index": 0,
                    "markdown": "เลขประจำตัวประชาชน* 1810800164491\nเลขประจำตัวนักเรียน 20018",
                    "confidence": 91,
                },
                {"index": 1, "markdown": "คำนำหน้านาม* เด็กชาย\nเพศ* ชาย", "confidence": 93},
            ],
            "confidence": 92,
            "usage": {"pages_processed": 2},
        }

    monkeypatch.setattr("dmc_sidecar.akson_ocr._upload_to_akson", fake_upload)

    response = ocr_dmc_form_with_akson(
        AksonOcrDmcFormRequest(source_path=str(source_path), api_key="secret", model="AksonOCR-1.0")
    )

    markdown_path = Path(response.markdown_path)
    assert response.cached is False
    assert response.pages_processed == 2
    assert response.average_confidence == 92
    assert markdown_path.exists()
    assert "Generated by DMC Assistant from AksonOCR" in markdown_path.read_text(encoding="utf-8")
    assert "เลขประจำตัวประชาชน* 1810800164491" in markdown_path.read_text(encoding="utf-8")

    cached_response = ocr_dmc_form_with_akson(AksonOcrDmcFormRequest(source_path=str(source_path)))

    assert cached_response.cached is True
    assert cached_response.markdown_path == response.markdown_path
    assert uploads == [source_path]


def test_ocr_dmc_form_with_akson_requires_api_key_when_not_cached(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setattr(config, "default_data_dir", lambda: tmp_path / "data")
    source_path = tmp_path / "form.pdf"
    source_path.write_bytes(b"%PDF-1.7\nsample dmc form\n")

    with pytest.raises(DomainError) as exc_info:
        ocr_dmc_form_with_akson(AksonOcrDmcFormRequest(source_path=str(source_path)))
    assert exc_info.value.code == "AKSONOCR_API_KEY_REQUIRED"


def test_ocr_dmc_form_with_akson_rejects_unsupported_file(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setattr(config, "default_data_dir", lambda: tmp_path / "data")
    source_path = tmp_path / "form.txt"
    source_path.write_text("not uploadable", encoding="utf-8")

    with pytest.raises(DomainError) as exc_info:
        ocr_dmc_form_with_akson(AksonOcrDmcFormRequest(source_path=str(source_path), api_key="secret"))
    assert exc_info.value.code == "AKSONOCR_UNSUPPORTED_INPUT_TYPE"
